### ISSUE TITLE
Look into nifti downsampling options

### ISSUE THREAD

**Issue by JohnGriffiths** [GriffithsLab/ConWhAt#3]
I (john) think there is some nifti image downsampling functionality in nilearn. 

- [x]  Find the functions
- [x]  Explore usage with conwhat atlas
- [x]  Save to file and check file sizes for different downsampling levels
- [x]  Compare downsampled vs. original atlas results

**Comment by zuxfoucault** [comment]
For the file: `CWL2k8Sc33Vol3d100s_v01/vismap_grp_8-9_norm.nii.gz`
Original file size: 223708
Adjusting the diagonal component of the affine matrix in Nilearn `resample_img` to get a different resampling ratio.
Multiply the diagonal component with 2 to downsample the image to get the size of 31999
Ratio 3 to downsample the image to get the size of 10039
Ratio 4 to downsample the image to get the size of 4594

Original image
![orinal_image](https://user-images.githubusercontent.com/3050531/106402984-4ffebb00-63fa-11eb-9095-20da357b652a.png)

Downsampled image with ratio 4
![downsampled_image](https://user-images.githubusercontent.com/3050531/106403004-6278f480-63fa-11eb-8225-86fd87d5d576.png)

**Comment by zuxfoucault** [comment]
compare the original and downsampled image
![stat_map_diff](https://user-images.githubusercontent.com/3050531/107173003-c8362500-6994-11eb-9070-b1905412a0fe.png)

**Comment by JohnGriffiths** [comment]
Looking good! A few suggestions:

- Set the vmin and vmax to be exactly the same for both figs
- remove the cross hairs

**Comment by zuxfoucault** [comment]
Update:
![stat_map_diff](https://user-images.githubusercontent.com/3050531/107300974-85358980-6a48-11eb-8fb6-d54d6c6f2894.png)
