### ISSUE TITLE
Re-run examples in the library with downsampled atlas

### ISSUE THREAD

**Issue by zuxfoucault** [GriffithsLab/ConWhAt#5]

**Comment by zuxfoucault** [comment]
Downsampled stat map:
![stat_map_downsampled](https://user-images.githubusercontent.com/3050531/106643820-3ffced80-6558-11eb-9c44-eeb008101882.png)

**Comment by zuxfoucault** [comment]
Errors in `compute_hit_stats`
```
  File "begin2.py", line 98, in get_hit_stats
    lo_df,lo_nx = cw_vca.compute_hit_stats(lesion_file, idxs,n_jobs=4,
  File "/Users/zuxfoucault/SSD/Space/UofT/grifflab/conwhat/src/conWhAt/conwhat/atlas.py", line 225, in compute_hit_stats
    df_hit_stats = compute_vol_hit_stats(roi,self.vfms,self.bbox,
  File "/Users/zuxfoucault/SSD/Space/UofT/grifflab/conwhat/src/conWhAt/conwhat/utils/stats.py", line 52, in compute_vol_hit_stats
    hstats = Parallel(n_jobs=n_jobs,temp_folder=joblib_cache_dir)\
  File "/Users/zuxfoucault/SSD/Space/miniconda3/envs/conwhat/lib/python3.8/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/Users/zuxfoucault/SSD/Space/miniconda3/envs/conwhat/lib/python3.8/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/Users/zuxfoucault/SSD/Space/miniconda3/envs/conwhat/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/Users/zuxfoucault/SSD/Space/miniconda3/envs/conwhat/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Users/zuxfoucault/SSD/Space/miniconda3/envs/conwhat/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
ValueError: operands could not be broadcast together with shapes (182,218,182) (47,56,47)
```

Updates:
Downsampling the T1 image to make volume shape match  
```
t1_mni_img = nib.load(t1_mni_file)
t1_mni_img = downsampling(t1_mni_img)
```
```
def downsampling(orig_nii, downsample_ratio=4):
    target_affine = np.eye(3)*downsample_ratio
    target_affine[0, 0] *= -1
    return resample_img(orig_nii, target_affine=target_affine,
                        interpolation='nearest')
```

**Comment by zuxfoucault** [comment]
There seems to be something wrong with hit stats:
for code:
```
lo_df, lo_nx = cw_vca.compute_hit_stats(lesion_file, idxs, n_jobs=4, joblib_cache_dir=jlc_dir)
tpr_adj = nx.to_pandas_adjacency(lo_nx, weight='TPR')
```
output:
```
In [4]: tpr_adj.values
Out[4]:
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [5]: np.unique(tpr_adj.values)
Out[5]: array([0.       , 0.0093633])

In [8]: tpr_adj.values.shape
Out[8]: (83, 83)
```

**Comment by zuxfoucault** [comment]
Scatter plot looks like:
![conwhat_scatter_diff](https://user-images.githubusercontent.com/3050531/107320038-eb80d300-6a6d-11eb-9ee2-533823a21337.png)

**Comment by zuxfoucault** [comment]
Downsampled synthetic lesion image:
![synthetic_lesion_20mm_sphere_-46_-60_6_d](https://user-images.githubusercontent.com/3050531/107422758-6f2bd580-6ae9-11eb-8803-47fdac731a90.png)

**Comment by zuxfoucault** [comment]
@JohnGriffiths In the original scatter image, the bounding box didn't cover the whole track. I found it after rotating the image.
<img width="1134" alt="Screen Shot 2021-02-11 at 10 20 26" src="https://user-images.githubusercontent.com/3050531/107657918-9f8f8300-6c53-11eb-8083-be4d306388ae.png">

**Comment by JohnGriffiths** [comment]
Ok good job!

Q then is why.

It should cover the whole tract.

**Comment by zuxfoucault** [comment]
I think there's a typo in the z-axis https://github.com/GriffithsLab/ConWhAt/blob/master/conwhat/utils/stats.py#L283

once it got fixed, the bounding box encloses the whole tract.
<img width="759" alt="Screen Shot 2021-02-15 at 15 02 06" src="https://user-images.githubusercontent.com/3050531/107989203-c3c6c900-6f9f-11eb-8e78-21ef928b0a46.png">

the `bounding_boxes.txt` that comes with the atlas also has the same value in `xmax` and `zmax`.

**Comment by JohnGriffiths** [comment]
Well spotted!

**Comment by zuxfoucault** [comment]
` np.corrcoef(tpr_adj.values.ravel(), cpr_adj.values.ravel())`
original:
```
[[1.         0.96272442]
 [0.96272442 1.        ]]
```
downsampled:
```
[[1.         0.96188826]
 [0.96188826 1.        ]]
```

`tpr and cpr heatmaps`
original:
![heatmap](https://user-images.githubusercontent.com/3050531/108019069-5fc7f300-6fe7-11eb-9b13-604691522f51.png)

downsampled:
![heatmap_d](https://user-images.githubusercontent.com/3050531/108019091-68202e00-6fe7-11eb-92df-d065d5cee5f0.png)

ps. after downsampling, we need to recalculate the bounding boxes for each track to produce the above downsampled results.
