### ISSUE TITLE
Simnibs lesion analysis

### ISSUE THREAD

**Issue by JohnGriffiths** [GriffithsLab/ConWhAt#7]
- [ ] Look at simnibs software; play with python api
- [ ] Connect with john and shrey re: usage for DLPFC TMS coordinates
- [ ] Run conwhat analysis on simnibs e-field volumes

**Comment by zuxfoucault** [comment]
`plot_roi` ernie's (example subject) head mesh on  MNI152
![synthetic_efield_ernie_mni](https://user-images.githubusercontent.com/3050531/109015332-044ed280-7683-11eb-98b6-413e1e5e160a.png)

**Comment by zuxfoucault** [comment]
Crop the mesh so we only have gray matter volume elements (tag 2 in the mesh)
![synthetic_efield_ernie_mni](https://user-images.githubusercontent.com/3050531/109031023-53e8ca80-7692-11eb-84d7-5ce717487b72.png)
ps. the misalignment is due to the native (subject) space where the gray matter is defined. Once coverting the volume to mni space, the offset is gone    

I think we should use both gray and white matter elements? and continue to find ways to extract both elements.

**Comment by zuxfoucault** [comment]
gray and white matter elements in e-field
![synthetic_efield_ernie_mni](https://user-images.githubusercontent.com/3050531/109524059-06979f00-7a7e-11eb-8249-1208eb4af307.png)

**Comment by zuxfoucault** [comment]
threshold with factor 0.6, and run the heatmap
![synthetic_efield_ernie_mni_thr](https://user-images.githubusercontent.com/3050531/109524965-0d72e180-7a7f-11eb-9f6b-a7a8d24e489d.png)

heatmap
![heatmap_efield](https://user-images.githubusercontent.com/3050531/109525004-1794e000-7a7f-11eb-8a28-0559193dbe40.png)

**Comment by JohnGriffiths** [comment]
This is awesome!

**Comment by JohnGriffiths** [comment]
To do: plot the connectivity matrix data on a brain. How to do that? take the row- or column- sum, and plot on brain as ROI colour intensities. Interpretation = brain regions with most connections impacted by this TMS stim. Naturally the hotspot will be the region directly underneath the stim. Interesting Q is: are there other regions that have lots of cnxns going through that stim target that are far away?

**Comment by zuxfoucault** [comment]
I'm trying to find where the 83 rois to volume mapping?

**Comment by JohnGriffiths** [comment]
See here

https://github.com/GriffithsLab/ctwc-model/blob/master/notebooks/03_focal_Io_stimulation.ipynb

This generates surface plots using lausanne 2008 scale 1 parc (83 nodes; 68 cortical). Note that the 68 cortical nodes are the same as the freesurfer Desikan-Killiany parcelation, but re-ordered.  

You might not have access to the necessary files. lmk if you need some that aren't in the repo.

**Comment by zuxfoucault** [comment]
F3, FP1, C3, C4, T3, T4
